repositories:
  - owner: department-of-veterans-affairs
    name: vets-api
    display_name: vets-api (Backend)
    backend_review_required: true
    
  - owner: department-of-veterans-affairs
    name: platform-atlas
    display_name: platform-atlas
    backend_review_required: false
    
  # vets-json-schema disabled for now
  # - owner: department-of-veterans-affairs
  #   name: vets-json-schema
  #   display_name: vets-json-schema
  #   backend_review_required: false

  - owner: department-of-veterans-affairs
    name: vets-api-mockdata
    display_name: vets-api-mockdata
    backend_review_required: false